"""support pending devices

Revision ID: 678f6aaea107
Revises: e6ea95f70ac5
Create Date: 2026-08-20 12:19:33.273194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678f6aaea107'
down_revision: Union[str, Sequence[str], None] = 'e6ea95f70ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('devices', 'os',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('devices', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices', 'os',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('devices', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
