"""add compute metrics

Revision ID: 6fedf902e14f
Revises: 249a12c1243d
Create Date: 2026-09-12 01:31:12.533517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fedf902e14f'
down_revision: Union[str, Sequence[str], None] = '249a12c1243d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('cpu_cores', sa.Integer(), nullable=True))
    op.add_column('heartbeats', sa.Column('cpu_threads', sa.Integer(), nullable=True))
    op.add_column('heartbeats', sa.Column('cpu_frequency_mhz', sa.Float(), nullable=True))
    op.add_column('heartbeats', sa.Column('uptime_seconds', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heartbeats', 'uptime_seconds')
    op.drop_column('heartbeats', 'cpu_frequency_mhz')
    op.drop_column('heartbeats', 'cpu_threads')
    op.drop_column('heartbeats', 'cpu_cores')
    # ### end Alembic commands ###
