"""create heartbeats table

Revision ID: 776a55ba3589
Revises: d14e2c5e2623
Create Date: 2026-08-13 11:03:22.603971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776a55ba3589'
down_revision: Union[str, Sequence[str], None] = 'd14e2c5e2623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.Integer(), nullable=True),
    sa.Column('disk_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_device_id'), 'heartbeats', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_device_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
