"""add device pairing fields

Revision ID: 94f1dfc66a01
Revises: 00c9eda547ec
Create Date: 2026-08-12 18:40:08.710037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f1dfc66a01'
down_revision: Union[str, Sequence[str], None] = '00c9eda547ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('pairing_code', sa.String(length=6), nullable=True))
    op.add_column('devices', sa.Column('pairing_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_devices_pairing_code'), 'devices', ['pairing_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_pairing_code'), table_name='devices')
    op.drop_column('devices', 'pairing_expires_at')
    op.drop_column('devices', 'pairing_code')
    # ### end Alembic commands ###
