"""add device storage

Revision ID: f2eb61a64480
Revises: c8a7d506f321
Create Date: 2026-09-12 01:40:35.465322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2eb61a64480'
down_revision: Union[str, Sequence[str], None] = 'c8a7d506f321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('mount_point', sa.String(length=255), nullable=False),
    sa.Column('filesystem', sa.String(length=100), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('free_bytes', sa.BigInteger(), nullable=False),
    sa.Column('usage_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_storage_device_id'), 'device_storage', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_storage_device_id'), table_name='device_storage')
    op.drop_table('device_storage')
    # ### end Alembic commands ###
